global using Mapster;
global using BuildingBlocks.CQRS;
global using Ordering.Application.Dtos;
global using FluentValidation;
global using MediatR;
global using Ordering.Domain.Events;
global using Microsoft.EntityFrameworkCore;
global using Ordering.Application.Data;
global using Ordering.Application.Extensions;